# Generated by Django 5.0.3 on 2024-04-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_alter_comment_options_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='Tracking.task'),
        ),
    ]
