# Generated by Django 5.0.3 on 2024-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_alter_workspace_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='task',
        ),
        migrations.AddField(
            model_name='workspace',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='Tracking.task'),
        ),
    ]
