# Generated by Django 5.0.3 on 2024-04-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0009_remove_workspace_tasks_workspace_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='Tracking.workspace'),
        ),
    ]
