# Generated by Django 5.0.3 on 2024-04-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0011_workspace_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_img',
            field=models.ImageField(blank=True, null=True, upload_to='TaskTracking/'),
        ),
    ]
